apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-spring-boot
spec:
  selector:
    matchLabels:
      pod: gs-spring-boot
  replicas: 1
  template:
    metadata:
      labels:
        pod: gs-spring-boot
    spec:
      containers:
        - image: gs-spring-boot
          name: gs-spring-boot
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot
spec:
  type: NodePort
  selector:
    pod: gs-spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31179
