apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot
spec:
  type: NodePort
  selector:
    pod: gs-spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31179
